//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRezervacija
{


    public partial class AdminUspesnaPrijava
    {

        protected global::System.Web.UI.WebControls.Label lblKorisnickoIme;
        protected global::System.Web.UI.WebControls.Button btnSobe;
        protected global::System.Web.UI.WebControls.Button btnRezervacije;
    }
}
