//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRezervacija
{


    public partial class AdminPrijava
    {

      
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblKorisnickoIme;
        protected global::System.Web.UI.WebControls.TextBox txtKorisnickoIme;
        protected global::System.Web.UI.WebControls.Label lblLozinka;
        protected global::System.Web.UI.WebControls.TextBox txtLozinka;
        protected global::System.Web.UI.WebControls.Button btnPrijavi;
    }
}
