//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRezervacija
{


    public partial class GostRegistracija
    {

        protected global::System.Web.UI.WebControls.Label lblPoruka;
        protected global::System.Web.UI.WebControls.TextBox txtJMBG;
        protected global::System.Web.UI.WebControls.TextBox txtIme;
        protected global::System.Web.UI.WebControls.TextBox txtPrezime;
        protected global::System.Web.UI.WebControls.DropDownList ddlPol;
        protected global::System.Web.UI.WebControls.TextBox txtDatumRodjenja;
        protected global::System.Web.UI.WebControls.TextBox txtBrojTelefona;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnRegistruj;
    }
}
