//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRezervacija
{


    public partial class PrijavaRezervacije
    {

       
        protected global::System.Web.UI.WebControls.Label lblPoruka;
        protected global::System.Web.UI.WebControls.TextBox txtJMBG;
        protected global::System.Web.UI.WebControls.DropDownList ddlBrojSobe;
        protected global::System.Web.UI.WebControls.TextBox txtDatumPrijave;
        protected global::System.Web.UI.WebControls.TextBox txtDatumOdjave;
        protected global::System.Web.UI.WebControls.Button btnRezervisi;
    }
}
