//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRezervacija
{


    public partial class Soba
    {

       
        protected global::System.Web.UI.WebControls.HiddenField hfIdSobe;
        protected global::System.Web.UI.WebControls.TextBox txtBrojSobe;
        protected global::System.Web.UI.WebControls.TextBox txtTipSobe;
        protected global::System.Web.UI.WebControls.TextBox txtKapacitet;
        protected global::System.Web.UI.WebControls.TextBox txtCenaPoNoci;
        protected global::System.Web.UI.WebControls.Button btnDodaj;
        protected global::System.Web.UI.WebControls.Button btnIzmeni;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblPoruka;
        protected global::System.Web.UI.WebControls.GridView gvSobe;
    }
}
