//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRezervacija
{


    public partial class UpravljanjeRegistracijama
    {

        protected global::System.Web.UI.WebControls.DropDownList ddlPol;
        protected global::System.Web.UI.WebControls.Button btnFiltriraj;
        protected global::System.Web.UI.WebControls.DropDownList ddlJmbgStamp;
        protected global::System.Web.UI.WebControls.Button btnStampaPoJmbg;
        protected global::System.Web.UI.WebControls.Button btnStampaSve;
        protected global::System.Web.UI.WebControls.GridView gvRegistracije;
    }
}
